"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import Image from "next/image";
import SearchBar from "@/components/search-bar";
import { Sparkles, ArrowRight, Wand2 } from "lucide-react";

// Curated high-aesthetic images for the scrolling cascade
const CASCADE_IMAGES_LEFT = [
  { src: "/ai-generated-chip.avif", alt: "Close-up macro photography of a high-tech glowing microchip processor" },
  { src: "/ai-generated-car.avif", alt: "Sleek metallic sports car created by an advanced AI image generator" },
  { src: "/ai-generated-food.avif", alt: "Hyper-detailed and appetizing culinary food photography generated by AI" },
  { src: "/ai-generated-moon.avif", alt: "Breathtaking AI generated close-up of the moon and cosmic deep space" },
];

const CASCADE_IMAGES_RIGHT = [
  { src: "/ai-generated-cycle.avif", alt: "Cyberpunk style futuristic motorcycle rendered with glowing neon lights" },
  { src: "/ai-generated-robot.avif", alt: "Highly detailed sci-fi robotic humanoid figure generated by artificial intelligence" },
  { src: "/ai-generated-boy.avif", alt: "Striking AI generative art depicting a young boy in a cinematic setting" },
  { src: "/ai-generated-women.avif", alt: "Hyper-realistic AI generated portrait of a beautiful woman with futuristic lighting" },

];

export default function HomeHero() {
  return (
    <section
      id="hero"
      aria-label="PromptStudio — Visual AI Prompt Gallery"
      className="relative w-full min-h-[100svh] flex items-center justify-center overflow-hidden bg-[#03010a] pt-24"
    >
      {/* Background Ambience */}
      <div className="absolute top-0 left-[-10%] w-[50%] aspect-square rounded-full bg-brand-purple/10 blur-[150px] pointer-events-none" />
      <div className="absolute bottom-[-20%] right-[-10%] w-[60%] aspect-square rounded-full bg-brand-cyan/10 blur-[150px] pointer-events-none" />
      <div className="absolute inset-0 z-0 bg-[linear-gradient(to_right,#ffffff03_1px,transparent_1px),linear-gradient(to_bottom,#ffffff03_1px,transparent_1px)] bg-[size:64px_64px] pointer-events-none" />

      <div className="relative z-10 w-full max-w-[1400px] mx-auto px-6 lg:px-12 grid lg:grid-cols-2 gap-16 lg:gap-8 items-center h-full">

        {/* Left Column: Typography & Actions */}
        <div className="flex flex-col items-center lg:items-start text-center lg:text-left pt-10 lg:pt-0">
          <motion.div
            initial={{ opacity: 0, scale: 0.9, originX: 0 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
            className="inline-flex items-center gap-2.5 px-4 py-2 rounded-full border border-white/10 bg-white/5 backdrop-blur-md text-gray-300 mb-8 text-sm font-medium tracking-wide shadow-xl"
          >
            <Sparkles className="w-4 h-4 text-brand-cyan" />
            <span className="bg-gradient-to-r from-gray-200 to-gray-400 bg-clip-text text-transparent">Next-Gen Visual Gallery</span>
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1, duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
            className="text-5xl sm:text-7xl lg:text-[5.5rem] font-bold tracking-tighter text-white leading-[1.05] mb-6"
          >
            Imagine. <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-cyan via-purple-400 to-brand-purple">
              Generate.
            </span>
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2, duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
            className="text-lg lg:text-xl text-gray-400 mb-10 max-w-lg font-light leading-relaxed"
          >
            Access thousands of breathtaking AI prompts, copy them for use in any platform, or generate your own images using Gemini right here in the browser.
          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3, duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
            className="w-full max-w-lg relative mb-10 z-20 group"
          >
            <div className="absolute -inset-1 bg-gradient-to-r from-brand-cyan to-brand-purple rounded-2xl blur-lg opacity-25 group-hover:opacity-40 transition-opacity duration-500" />
            <div className="relative">
              <SearchBar />
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4, duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
            className="flex flex-wrap items-center justify-center lg:justify-start gap-4 w-full"
          >
            <Link
              href="/explore"
              className="flex items-center justify-center gap-2 px-8 py-4 bg-white text-black font-semibold rounded-full text-base transition-all hover:scale-105 active:scale-95 shadow-[0_0_30px_rgba(255,255,255,0.2)]"
            >
              Start Exploring <ArrowRight className="w-4 h-4" />
            </Link>
            <Link
              href="/generate"
              className="flex items-center justify-center gap-2 px-8 py-4 border border-white/10 bg-white/5 backdrop-blur-md text-white font-medium rounded-full text-base transition-all hover:bg-white/10 hover:scale-105 active:scale-95"
            >
              <Wand2 className="w-4 h-4 text-brand-purple" />
              Generate Image
            </Link>
          </motion.div>
        </div>

        {/* Right Column: Dynamic Scrolling Image Cascades */}
        <div className="relative h-[80svh] w-full hidden md:flex items-center justify-center gap-4 lg:gap-6 overflow-hidden perspective-[1200px] [mask-image:linear-gradient(to_bottom,transparent,black_10%,black_90%,transparent)]">
          {/* Subtle Rotate/Tilt Container for 3D Feel */}
          <div className="flex gap-4 lg:gap-6 w-full h-[200%] rotate-[-4deg] scale-[1.05] translate-x-10">

            {/* Cascade Column 1 (Scrolls Up) */}
            <div
              className="flex flex-col flex-1 mt-12 animate-cascade-up"
            >
              {[1, 2].map((group) => (
                <div key={group} className="flex flex-col gap-4 lg:gap-6 pb-4 lg:pb-6">
                  {CASCADE_IMAGES_LEFT.map((item, idx) => (
                    <div
                      key={`left-${group}-${idx}`}
                      className="relative aspect-[3/4] rounded-2xl overflow-hidden border border-white/10 shadow-[0_20px_50px_rgba(0,0,0,0.5)] transform-gpu hover:scale-[1.02] transition-transform duration-500"
                    >
                      <Image src={item.src} alt={item.alt} fill sizes="(max-width: 768px) 100vw, 30vw" className="object-cover" priority />
                      <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 hover:opacity-100 transition-opacity duration-300" />
                    </div>
                  ))}
                </div>
              ))}
            </div>

            {/* Cascade Column 2 (Scrolls Down) */}
            <div
              className="flex flex-col flex-1 -mt-24 animate-cascade-down"
            >
              {[1, 2].map((group) => (
                <div key={group} className="flex flex-col gap-4 lg:gap-6 pb-4 lg:pb-6">
                  {CASCADE_IMAGES_RIGHT.map((item, idx) => (
                    <div
                      key={`right-${group}-${idx}`}
                      className="relative aspect-[4/5] rounded-2xl overflow-hidden border border-white/10 shadow-[0_20px_50px_rgba(0,0,0,0.5)] transform-gpu hover:scale-[1.02] transition-transform duration-500"
                    >
                      <Image src={item.src} alt={item.alt} fill sizes="(max-width: 768px) 100vw, 30vw" className="object-cover" priority />
                      <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 hover:opacity-100 transition-opacity duration-300" />
                    </div>
                  ))}
                </div>
              ))}
            </div>

          </div>
        </div>

      </div>
    </section>
  );
}
