"use client";

import { motion } from "framer-motion";
import { Search, ImagePlus, CheckCircle2 } from "lucide-react";

const STEPS = [
  {
    step: "01",
    icon: Search,
    title: "Find Your Aesthetic",
    detail:
      "Browse thousands of stunning visual prompts generated by expert digital artists. Filter by Midjourney, DALL-E, style, lighting, or specific subjects to find the perfect reference.",
    tag: "Free Visual Gallery",
    color: "text-brand-cyan",
    glow: "shadow-[0_0_40px_rgba(0,212,255,0.08)]",
    border: "border-brand-cyan/20",
  },
  {
    step: "02",
    icon: ImagePlus,
    title: "Copy & Generate",
    detail:
      "Copy the exact prompt to deploy in Discord/Midjourney, or use our built-in generator engine powered by the Gemini API. Breathtaking images straight from your browser.",
    tag: "Gemini API Ready",
    color: "text-brand-purple",
    glow: "shadow-[0_0_40px_rgba(124,58,237,0.08)]",
    border: "border-brand-purple/20",
  },
  {
    step: "03",
    icon: CheckCircle2,
    title: "Share Your Vision",
    detail:
      "Did you discover an amazing prompt? Add your generative art to our growing gallery. Build your reputation as an elite prompt creator and inspire millions of artists globally.",
    tag: "Join The Community",
    color: "text-brand-pink",
    glow: "shadow-[0_0_40px_rgba(236,72,153,0.08)]",
    border: "border-brand-pink/20",
  },
];

export default function HowItWorksSection() {
  return (
    <section
      aria-label="How PromptStudio works — Browse visual art prompts, generate with Gemini, upload yours"
      className="py-32 w-full mx-auto px-4 sm:px-8 relative"
    >
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 w-[800px] h-full bg-brand-purple/5 blur-[120px] rounded-full pointer-events-none -z-10" />

      <div className="text-center mb-24">
        <span className="text-sm font-bold tracking-widest uppercase text-[#a855f7] block mb-5">Seamless Pipeline</span>
        <h2 className="text-5xl md:text-6xl font-extrabold tracking-tight text-white mb-6">
          How To Create Art
        </h2>
        <p className="text-gray-400 text-xl w-full mx-auto font-light leading-relaxed">
          Go from browsing beautiful imagery to generating your own cinematic masterpieces in seconds.
        </p>
      </div>

      <div className="relative grid grid-cols-1 md:grid-cols-3 gap-10">
        <div className="hidden md:block absolute top-12 left-[calc(16.67%+2rem)] right-[calc(16.67%+2rem)] h-px bg-gradient-to-r from-brand-cyan/20 via-brand-purple/40 to-brand-pink/20 z-0" />

        {STEPS.map((s, i) => {
          const Icon = s.icon;
          return (
            <motion.div
              key={s.step}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.55, delay: i * 0.15, ease: [0.22, 1, 0.36, 1] }}
              className={`relative flex flex-col items-center text-center p-10 rounded-[2rem] bg-[#0a0812] border ${s.border} ${s.glow} z-10 hover:-translate-y-2 transition-transform duration-500`}
            >
              <div className={`w-14 h-14 rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center mb-8 relative z-20 shadow-lg`}>
                <Icon className={`w-6 h-6 ${s.color}`} />
              </div>

              <div className={`text-6xl font-black ${s.color} opacity-10 absolute top-8 right-8 select-none leading-none tracking-tighter`}>
                {s.step}
              </div>

              <h3 className="text-2xl font-bold text-white mb-4">{s.title}</h3>
              <p className="text-sm text-gray-400 leading-relaxed mb-6 font-light">{s.detail}</p>
              
              <div className="mt-auto">
                <span className={`text-xs font-bold uppercase tracking-widest ${s.color} bg-white/5 px-4 py-2 rounded-lg border ${s.border}`}>
                  {s.tag}
                </span>
              </div>
            </motion.div>
          );
        })}
      </div>
    </section>
  );
}
